amqp:
  admin:
    auto-create: true
  queues:
    video-created:
      exchange: video.events
      routing-key: video.created
      queue: video.created.queue
    video-encoded:
      exchange: video.events
      routing-key: video.encoded
      queue: video.encoded.queue
---
spring:
  application:
#    name: Admin Catalogo
    name: Codeflix
  jpa:
    open-in-view: false
    show-sql: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disabled_autocommit]": true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_MYSQL_URL}/${DATABASE_MYSQL_DB}
    username: ${DATABASE_MYSQL_USER}
    password: ${DATABASE_MYSQL_PASS}
  hikari:
    auto-commit: false
    connection-timeout: 250 #milisegundos
    max-lifetome: 600000 #Tempo máximo que uma conexão fica aberta (10 minutos)
    maximun-pool-size: 20 # Qunatidade de conexões para manter abertas
    minimum-idle: 10
    pool-name: master
  rabbitmq:
    dynamic: ${amqp.admin.auto-create}
    host: ${AMQP_RABBIT_HOST}
    port: ${AMQP_RABBIT_PORT}
    username: ${AMQP_RABBIT_USER}
    password: ${AMQP_RABBIT_PASS}
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 100GB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.host}/realms/${keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak.host}/realms/${keycloak.realm}
---
springdoc:
  swagger-ui:
    path: /api-doc.html
---
server:
  port: 8090
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4
---
storage:
  catalogo-videos:
    location-pattern: videoId-{videoId}
    filename-pattern: type-{type}
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DATABASE_MYSQL_URL}/${DATABASE_MYSQL_DB}_dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
storage:
  catalogo-videos:
    local-storage-path: C:\\dev\\storage\\dev
---
spring:
  config:
    activate:
      on-profile: tst
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:adm_videos_tst
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
storage:
  catalogo-videos:
    local-storage-path: C:\\dev\\storage\\tst
keycloak:
  realm: codeflix
  host: http://keycloak:8080
---
spring:
  config:
    activate:
      on-profile: tst-int
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drpo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:adm_videos_tst
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
storage:
  catalogo-videos:
    local-storage-path: C:\\dev\\storage\\tst-int
keycloak:
  realm: codeflix
  host: http://keycloak:8080
---
spring:
  flyway:
    enabled: false
  config:
    activate:
      on-profile: tst-e2e
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:${E2E_MYSQL_PORT}/adm_videos_e2e
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
storage:
  catalogo-videos:
    local-storage-path: C:\\dev\\storage\\tst-e2e
keycloak:
  realm: codeflix
  host: http://keycloak:8080
---
spring:
  config:
    activate:
      on-profile: sbx
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DATABASE_MYSQL_URL}/${DATABASE_MYSQL_DB}_sbx
amqp:
  queues:
    video-created:
      exchange: video.events.sbx
      routing-key: video.created.sbx
      queue: video.created.queue.sbx
    video-encoded:
      exchange: video.events.sbx
      routing-key: video.encoded.sbx
      queue: video.encoded.queue.sbx
storage:
  catalogo-videos:
    local-storage-path: C:\\dev\\storage\\sbx
keycloak:
  realm: ${KEYCLOAK_REALM:codeflix}
  host: ${KEYCLOAK_HOST:http://keycloak:8080}
---
spring:
  config:
    activate:
      on-profile: prd
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${DATABASE_MYSQL_URL}/${DATABASE_MYSQL_DB}
storage:
  catalogo-videos:
    local-storage-path: C:\\dev\\storage\\prd
keycloak:
  realm: ${KEYCLOAK_REALM:codeflix}
  host: ${KEYCLOAK_HOST:http://localhost:8080}
