services:

  mysql:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    container_name: codeflix_mysql
    restart: always
    tty: true
    volumes:
      - ../.docker/mysql/codeflix:/var/lib/mysql:rw
    environment:
      MYSQL_USER: codeflix
      MYSQL_PASSWORD: C0d3Fl1x
      MYSQL_TCP_PORT: 3307
      MYSQL_DATABASE: adm_videos
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - 3307:3307
    expose:
      - 3307
    networks:
      - codeflix_services

  rabbitmq:
    container_name: codeflix_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: CODEFLIXRMQCOOKIE
      RABBITMQ_DEFAULT_USER: codeflix
      RABBITMQ_DEFAULT_PASS: C0d3Fl1x
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - codeflix_services

  keycloak:
    container_name: codeflix_keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    volumes:
      - ../.docker/keycloak/import:/opt/keycloak/data/import:rw
      - ../.docker/keycloak/h2:/opt/keycloak/data/h2:rw
      - ../.docker/keycloak/mysql:/var/lib/mysql:rw
    environment:
      KEYCLOAK_ADMIN: codeflix
      KEYCLOAK_ADMIN_PASSWORD: C0d3Fl1x
    ports:
      - 8080:8080
    command:
      - start-dev
      - --hostname=http://keycloak:8080
    networks:
      - codeflix_services

networks:
  codeflix_services:
    external: true