#version: '3.7'

services:
  app:
    container_name: codeflix_app
#   image: landucci/codeflix:0.1.6
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8090:8090
    labels:
      filebeat_collector: true
    depends_on:
      - filebeat
    networks:
      - codeflix_network
      - codeflix_services

  filebeat:
    container_name: codeflix_filebeat
    image: docker.elastic.co/beats/filebeat:7.17.9
    command: filebeat -e -strict.perms=false
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:rw           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:rw                       # Additional information about containers
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:rw # Configuration file
      - ../.docker/filebeat:/usr/share/filebeat/data:rw                    # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    networks:
      - codeflix_network
      - codeflix_elk

networks:
  codeflix_network:
  codeflix_services:
    external: true
  codeflix_elk:
    external: true