name: CI/CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: landucci/codeflix
  MAJOR_VERSION: 0
  MINOR_VERSION: 1

jobs:
  tests:
    name: Execução dos testes da aplicação
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Executando os testes da aplicação
        run: ./gradlew test

  build:
    name: Construção da aplicação
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Validando a versão do "Gradle Wrapper"
        uses: gradle/actions/wrapper-validation@v3
      - name: Construindo a aplicação
        uses: gradle/actions/setup-gradle@v3
        run: ./gradlew clean build -x test
      - name: Definindo a TAG da aplicação
        run: |
          echo BUILD_TAG=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.${{ github.run_number }} >> $GITHUB_ENV
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"
      - name: Conectando e autenticando no "DockerHub"
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: Construindo e publicando a iamgem no "DockerHub"
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}



