name: CI Pipeline

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Testes da aplicação
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Executar os testes da aplicação
        run: ./gradlew test

